### ISSUE TITLE
BOM file location for PCB fabrication

### ISSUE THREAD

**Issue by ImShomu** [Luisonson/LibreServo_v2#5]
Hi @Luisonson,

Thanks for the amazing work. Can you please share the BOM xls and the latest PCB file location?
I would like to fabricate and test it.
I think the latest PCB is here as of 2024 
1. https://github.com/Luisonson/LibreServo_v2/blob/master/PCB/LibreServo-v2.3.1.brd
2. https://github.com/Luisonson/LibreServo_v2/blob/master/PCB/LibreServo-v2.3.1.sch 

Best 
Shomu

**Comment by Luisonson** [comment]
Hello @ImShomu ,

I have uploaded the BOM file:
https://github.com/Luisonson/LibreServo_v2/blob/master/PCB/LibreServo-v2.3_BOM.txt

**Comment by ImShomu** [comment]
@Luisonson, thank you so much for the work! 

Can I consider this to be the final PCB upgrade and the rest will be firmware updates going on? 
Also one quick note, I was getting some errors when I opened the PCB in KICad. The 3D view was not coming correctly and KiCad was complaining about lot of errors in PCB.

**Comment by Luisonson** [comment]
Hello @ImShomu ,
Yes, it is the final version. There should not be any changes, hopefully 🤞🤞🤞
Unfortunately, Libreservo was made using a version of Eagle from 8 years ago and in those days, the 3D view didn't exist, so it's not there. If you want to make LibreServo, just upload the [Gerber](https://github.com/Luisonson/LibreServo_v2/tree/master/PCB/Gerbers/LibreServo%20v2.3.1) you want to JLCPCB (upload directly the .zip file you want).
Nowadays Eagle software sucks, so new PCBs, because I am working on new projects using the LibreServo standard like a new 2 DC smart motor controller, are made using Kicad.
![image](https://github.com/Luisonson/LibreServo_v2/assets/12425566/34776ac1-3da9-4d9d-b9b9-724d9401aea5)

**Comment by Luisonson** [comment]
If you need help in making LibreServo in JLCPCB, I can create a small help article.

**Comment by Shomu-Maersk** [comment]
@Luisonson, that will be a lifesaver. 

Also can you please upload the BOM in .csv format? 
I tried to order the PCB via JLCPCB with components insertion.  They asked for a component placement file along with BOM file. 
If you can help with that would be awesome!!

Best Shomu

**Comment by ImShomu** [comment]
Also can you please upload the BOM in .csv format? I tried to order the PCB via JLCPCB with components insertion. They asked for a component placement file along with BOM file. If you can help with that would be awesome!!
Best Shomu

**Comment by Luisonson** [comment]
Hello @ImShomu ,

I have to say that I have never asked for a component placement in any of my projects...

Here is the bom in CSV format (it is the same but adding a ';' as column separator) 😉 

[LibreServo-v2.3_BOM.csv](https://github.com/user-attachments/files/16162701/LibreServo-v2.3_BOM.csv)

Note that not all the parts are in LCSC, they don't have the LED, the current sensor neither the encoder.

If you have to make another file to JLCPCB or something special, I would like to hear from you so I can add it to the documentation, please 😄
